services:
  db:
    image: postgres:16
    container_name: condo_postgres
    environment:
      POSTGRES_USER: condo
      POSTGRES_PASSWORD: condo123
      POSTGRES_DB: condo
    ports:
      - "5433:5432"
    volumes:
      - condo_pgdata:/var/lib/postgresql/data

volumes:
  condo_pgdata:
